### ISSUE TITLE
关于已经复现的exp

### ISSUE THREAD

**Issue by FunnyWolf** [Ascotbe/Kernelhub#1]
readme中有提及那些cve没有复现,是否可以在readme中列出那些cve(exp)已经复现通过了,包括在哪些平台复现了.

**Comment by Ascotbe** [comment]
> readme中有提到那些cve没有复现，是否可以在readme中列出那些cve（exp）已经复现通过了，包括在某些平台复现了。

除了没有复现的成功的都是成功了的呀，平台什么的你直接点进去CVE就能看到
