### ISSUE TITLE
Python 3.9 全新环境，依旧报错

### ISSUE THREAD

**Issue by TryA9ain** [Ascotbe/Kernelhub#2]
![image](https://user-images.githubusercontent.com/51145610/99631524-b7050880-2a76-11eb-9382-6a97bf144944.png)
![image](https://user-images.githubusercontent.com/51145610/99631869-4d392e80-2a77-11eb-94b7-01987433e16a.png)

python3.7.5也报错，请问大佬的复现环境是什么呢？

**Comment by Ascotbe** [comment]
写的很清楚了，看文档
